SELECT DISTINCT T1.COMP_NAME,
	(SELECT (SELECT SUM(GC_MIK) FROM DNMHAR WHERE T1.ID=DNMHAR.COMP_ID AND DNMHAR.HAR_TYPE='G' )-(SELECT SUM(GC_MIK) FROM DNMHAR WHERE T1.ID=DNMHAR.COMP_ID AND DNMHAR.HAR_TYPE='C' ))
FROM DNMNAMES T1
INNER JOIN DNMHAR T2 ON T1.ID = T2.COMP_ID